version: 2
jobs:
  lint:
    docker:
      - image: circleci/node:14.15
    steps:
      - checkout
      - run: yarn install
      - run: yarn lint
  build:
    docker:
      - image: circleci/node:14.15
    resource_class: medium+
    steps:
      - checkout
      - run:
            name: Setup dotenv
            command: echo "SOME_DOTENV_VAR=$SOME_DOTENV_VAR" > .env
      - run: yarn install
      - run: yarn build
  test:
    docker:
      - image: circleci/node:14.15
    resource_class: medium+
    steps:
      - checkout
      - run: yarn install
      - run: yarn test
workflows:
  version: 2
  lint_build_test:
    jobs:
      - lint
      - build
      - test
