Resources:
# DynamoDB
    DynamoDBTableTEMPLATE_NAME:
        Type: AWS::DynamoDB::Table
        DeletionPolicy: ${self:custom.common.deletionPolicy}
        Properties:
            TableName: ${self:custom.dynamoDb.tableName}
            BillingMode: ${self:custom.dynamoDb.billingMode}
            AttributeDefinitions:
                - AttributeName: pk
                  AttributeType: S
                - AttributeName: sk
                  AttributeType: S
                - AttributeName: pk1
                  AttributeType: S
                - AttributeName: sk1
                  AttributeType: S
            KeySchema:
                - AttributeName: pk
                  KeyType: HASH
                - AttributeName: sk
                  KeyType: RANGE
            GlobalSecondaryIndexes:
                - IndexName: GSI1
                  KeySchema:
                    - AttributeName: pk1
                      KeyType: HASH
                    - AttributeName: sk1
                      KeyType: RANGE
                  Projection:
                    ProjectionType: INCLUDE
                    NonKeyAttributes:
                      - data
