service: be-TEMPLATE_NAME-service

custom:
    stage: ${opt:stage, "development"}
    s3:
        bucketName: be-TEMPLATE_NAME-bucket-${self:custom.stage}
    dynamoDb:
        tableName: be-TEMPLATE_NAME-${self:custom.stage}
        billingMode: PAY_PER_REQUEST
    common:
        deletionPolicies:
            development: Delete
            default: Retain
        deletionPolicy: ${self:custom.common.deletionPolicies.${self:custom.stage}, self:custom.common.deletionPolicies.default}
    authorizer:
        name: authorizer
        identitySource: method.request.header.Authorization
        type: token
    webpack:
        webpackConfig: ./webpack.config.js
        packager: 'yarn'

package:
  individually: true

### PLUGINS

plugins:
    - serverless-iam-roles-per-function
    - serverless-webpack
    - serverless-offline

### RESOURCES

resources:
    - ${file(./infrastructure/resources/DB.yml)}
    - ${file(./infrastructure/resources/S3.yml)}

### PROVIDER

provider:
    name: aws
    runtime: nodejs12.x
    region: ca-central-1
    stage: ${self:custom.stage}
    environment:
        AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
        REGION: ${self:provider.region}
        S3_BUCKET_NAME: ${self:custom.s3.bucketName}
        DYNAMODB_TABLE: ${self:custom.dynamoDb.tableName}

### FUNCTIONS

functions:
    authorizer:
        handler: src/functions/authorizer/index.default

    list:
        handler: src/functions/list/index.default
        iamRoleStatementsName: TEMPLATE_NAME-${self:custom.stage}-list-role
        iamRoleStatements:
          - Effect: "Allow"
            Action:
              - dynamodb:Query
            Resource: "arn:aws:dynamodb:::table/${self:custom.dynamoDb.tableName}"
        events:
            - http:
                path: /TEMPLATE_NAME/
                method: get
                cors: true
                authorizer: ${self:custom.authorizer}

    create:
        handler: src/functions/create/index.default
        iamRoleStatementsName: TEMPLATE_NAME-${self:custom.stage}-create-role
        iamRoleStatements:
          - Effect: "Allow"
            Action:
              - dynamodb:PutItem
            Resource: "arn:aws:dynamodb:::table/${self:custom.dynamoDb.tableName}"
        events:
            - http:
                path: /TEMPLATE_NAME/
                method: post
                cors: true
                authorizer: ${self:custom.authorizer}

    put:
        handler: src/functions/put/index.default
        iamRoleStatementsName: TEMPLATE_NAME-${self:custom.stage}-put-role
        iamRoleStatements:
          - Effect: "Allow"
            Action:
              - dynamodb:PutItem
            Resource: "arn:aws:dynamodb:::table/${self:custom.dynamoDb.tableName}"
        events:
            - http:
                path: /TEMPLATE_NAME/{TEMPLATE_NAME_SK}/
                method: put
                request:
                    parameters:
                        paths:
                            TEMPLATE_NAME_SK: true
                cors: true
                authorizer: ${self:custom.authorizer}

    get:
        handler: src/functions/get/index.default
        iamRoleStatementsName: TEMPLATE_NAME-${self:custom.stage}-get-role
        iamRoleStatements:
          - Effect: "Allow"
            Action:
              - dynamodb:GetItem
            Resource: "arn:aws:dynamodb:::table/${self:custom.dynamoDb.tableName}"
        events:
            - http:
                path: /TEMPLATE_NAME/{TEMPLATE_NAME_SK}/
                method: get
                request:
                    parameters:
                        paths:
                            TEMPLATE_NAME_SK: true
                cors: true
                authorizer: ${self:custom.authorizer}

    delete:
        handler: src/functions/delete/index.default
        iamRoleStatementsName: TEMPLATE_NAME-${self:custom.stage}-delete-role
        iamRoleStatements:
          - Effect: "Allow"
            Action:
              - dynamodb:DeleteItem
            Resource: "arn:aws:dynamodb:::table/${self:custom.dynamoDb.tableName}"
        events:
            - http:
                path: /TEMPLATE_NAME/{TEMPLATE_NAME_SK}/
                method: delete
                request:
                    parameters:
                        paths:
                            TEMPLATE_NAME_SK: true
                cors: true
                authorizer: ${self:custom.authorizer}

    upload:
        handler: src/functions/upload/index.default
        iamRoleStatementsName: TEMPLATE_NAME-${self:custom.stage}-upload-role
        iamRoleStatements:
          - Effect: "Allow"
            Action:
              - s3:PutObject
            Resource: "arn:aws:s3:::${self:custom.s3.bucketName}/*"
        events:
            - http:
                path: /TEMPLATE_NAME/upload/
                method: post
                cors: true
                authorizer: ${self:custom.authorizer}

    download:
        handler: src/functions/download/index.default
        iamRoleStatementsName: TEMPLATE_NAME-${self:custom.stage}-download-role
        iamRoleStatements:
          - Effect: "Allow"
            Action:
              - s3:GetObject
            Resource: "arn:aws:s3:::${self:custom.s3.bucketName}/*"
        events:
            - http:
                path: /TEMPLATE_NAME/download/{fileId}/
                method: get
                request:
                    parameters:
                        paths:
                            fileId: true
                cors: true
                authorizer: ${self:custom.authorizer}
