export enum Roles {
    TEMPLATE_NAME_ROLE1 = 'TEMPLATE_NAME_role1',
    TEMPLATE_NAME_ROLE2 = 'TEMPLATE_NAME_role2',
}

export const AUTH0_AUDIENCE = 'TEMPLATE_NAME_AUTH0_AUDIENCE'

export const AUTH0_DOMAIN = 'TEMPLATE_NAME_AUTH0_DOMAIN'

export const ROLES_CLAIM_KEY = 'TEMPLATE_NAME_AUTH0_ROLES_CLAIM_KEY'
