name: BE Template CI
on: push

jobs:
  lint:
    name: Run linters
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14.15.4'
        cache: 'yarn'
    - run: yarn install
    - run: yarn lint
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14.15.4'
        cache: 'yarn'
    - run: yarn install
    - run: yarn test
  build:
    name: Package functions
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14.15.4'
        cache: 'yarn'
    - name: Create .env file
      run: |
        touch .env
        echo SOME_DOTENV_VAR="some-dotenv-var" >> .env
        cat .env
    - run: yarn install
    - run: yarn build
