name: BE Template CI
on: push

jobs:
  lint:
    name: Run linters
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup NodeJS
      uses: actions/setup-node@v2
      with:
        node-version: '14.18.1'
        cache: 'yarn'
    - run: yarn install
    - run: yarn lint
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup NodeJS
      uses: actions/setup-node@v2
      with:
        node-version: '14.18.1'
        cache: 'yarn'
    - run: yarn install
    - run: yarn test
  build:
    name: Package functions
    runs-on: ubuntu-latest
    permissions:
        id-token: write
        contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup NodeJS
      uses: actions/setup-node@v2
      with:
        node-version: '14.18.1'
        cache: 'yarn'
    - name: Create .env file
      run: |
        touch .env
        echo SOME_DOTENV_VAR="some-dotenv-var" >> .env
        cat .env
    - run: yarn install
    - name: Configure Test account AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID_PRODUCTION }}:role/GitHubActionsRole
        aws-region: us-east-1
    - name: yarn build
      run: |
        export NODE_OPTIONS="--max_old_space_size=4096" && yarn build
