name: BE Template CD
on:
  workflow_run:
    workflows: ["BE Template CI"]
    branches: [master]
    types: [completed]

jobs:
#   deploy_staging:
#     name: Deploy functions to the staging environment
#     runs-on: ubuntu-latest
#     permissions:
#         id-token: write
#     if: ${{ github.event.workflow_run.conclusion == 'success' }}
#     steps:
#     - name: Checkout
#       uses: actions/checkout@v2
#     - name: Setup NodeJS
#       uses: actions/setup-node@v2
#       with:
#         node-version: '14.18.1'
#         cache: 'yarn'
#     - name: Configure Staging account AWS credentials
#       uses: aws-actions/configure-aws-credentials@v1
#       with:
#         role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID_STAGING }}:role/GitHubActionsRole
#         aws-region: us-east-1
#     - name: Create .env file
#       run: |
#         touch .env
#         echo SOME_DOTENV_VAR="some-dotenv-var-staging" >> .env
#         cat .env
#     - run: yarn install
#     - run: yarn deploy:staging
  deploy_production:
    name: Deploy functions to the production environment
    runs-on: ubuntu-latest
    permissions:
        id-token: write
    # needs: deploy_staging
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup NodeJS
      uses: actions/setup-node@v2
      with:
        node-version: '14.18.1'
        cache: 'yarn'
    - name: Configure Production account AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID_PRODUCTION }}:role/GitHubActionsRole
        aws-region: us-east-1
    - name: Create .env file
      run: |
        touch .env
        echo SOME_DOTENV_VAR="some-dotenv-var-prod" >> .env
        cat .env
    - run: yarn install
    - run: yarn deploy:production
